name: Synchronize HLRS Gitlab data

on:
  push:
    branches : ["dev","master","vlasiator_gpu"]

jobs:
  push_to_gitlab:
    # Run the testpackage on the carrington cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Push to Gitlab
      run: |
        git remote add gitlab https://oauth2:${token}@codehub.hlrs.de/coes/plasma-pepsc/uoh/vlasiator.git
        git fetch gitlab
        git push -f gitlab origin/master:master
        git push -f gitlab origin/dev:dev
        git push -f gitlab origin/vlasiator_gpu:vlasiator_gpu
      env:
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
